name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to GitHub Container Registry (GHCR)
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    # Build Docker Image
    - name: Build the Docker image
      run: |
        IMAGE_NAME="ghcr.io/${{ github.repository }}/matic-api:latest"
        IMAGE_NAME_LOWER=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')  # Ubah menjadi lowercase
        docker build . --file Dockerfile --tag $IMAGE_NAME_LOWER

    # Push Docker Image to GHCR
    - name: Push Docker image to GHCR
      run: |
        IMAGE_NAME="ghcr.io/${{ github.repository }}/matic-api:latest"
        IMAGE_NAME_LOWER=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')  # Ubah menjadi lowercase
        docker push $IMAGE_NAME_LOWER

    # Set image as public on GHCR
    - name: Set image as public on GHCR
      run: |
        IMAGE_NAME="ghcr.io/${{ github.repository }}/matic-api:latest"
        IMAGE_NAME_LOWER=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')  # Ubah menjadi lowercase
        curl -X PATCH \
          -H "Authorization: Bearer ${{ secrets.GHCR_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"visibility":"public"}' \
          https://api.github.com/repos/${{ github.repository }}/packages/container/matic-api/versions/latest

    # Optional: Run Docker container
    - name: Run Docker container
      run: |
        IMAGE_NAME="ghcr.io/${{ github.repository }}/matic-api:latest"
        IMAGE_NAME_LOWER=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')  # Ubah menjadi lowercase
        docker run --name matic-api -d $IMAGE_NAME_LOWER
        docker ps
